/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Checkered Floor Tile 8x8.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
// import {GLTF} from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     mesh735054256: THREE.Mesh
//     mesh735054256_1: THREE.Mesh
//   }
//   materials: {
//     mat23: THREE.MeshStandardMaterial
//     mat21: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

export default function CheckeredFloor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Checkered Floor Tile 8x8.glb'); // as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh735054256.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh735054256_1.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('/Checkered Floor Tile 8x8.glb')
