/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Crypto Bro.glb -T 
Files: Crypto Bro.glb [273.02KB] > /home/peter/dev/portfolio/app/models/Crypto Bro-transformed.glb [88.36KB] (68%)
*/

import React, { useEffect, useState } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function CryptoBro(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Crypto Bro-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, mixer } = useAnimations(animations, group);

  const [modelAction, setModelAction] = useState(false);

  useEffect(() => {
    if (modelAction == false) {
      // actions
      mixer.stopAllAction();
    } else {
      if (actions["Armature|Walk"]) {
        actions["Armature|Walk"].play();
      }
    }
  }, [modelAction, actions]);

  const toggleAnimation = () => {
    setModelAction((prev) => prev == true ? false: true);
  }

  return (
    <group ref={group} {...props} dispose={null} onClick={() => {toggleAnimation();}}>
      <group name="Root_Scene">
        <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.CORE} />
        </group>
        <skinnedMesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials.CryptoBro}
          skeleton={nodes.Cube001.skeleton}
          position={[0, 1.46, 0.59]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={56}
        />
        <skinnedMesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials.CryptoBro}
          skeleton={nodes.Cube003.skeleton}
          position={[0, 0.692, 0.068]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={56}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Crypto Bro-transformed.glb");
